// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpGMrtXJct-u-zXzvuaxZy-cTTbrqq6Fs',
    appId: '1:663055197483:web:fdb680541e59fea3aa116e',
    messagingSenderId: '663055197483',
    projectId: 'hoophub-aa29d',
    authDomain: 'hoophub-aa29d.firebaseapp.com',
    storageBucket: 'hoophub-aa29d.appspot.com',
    measurementId: 'G-1DG5STF91L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9uOgJ4RQdKitLi1sNWKo3BPbO4GxYF8g',
    appId: '1:663055197483:android:065ace1e1c84f929aa116e',
    messagingSenderId: '663055197483',
    projectId: 'hoophub-aa29d',
    storageBucket: 'hoophub-aa29d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyp1LwfVUlxErzDHHmTo4HkMD9Q1HyXqQ',
    appId: '1:663055197483:ios:5bff75e68e09dc93aa116e',
    messagingSenderId: '663055197483',
    projectId: 'hoophub-aa29d',
    storageBucket: 'hoophub-aa29d.appspot.com',
    iosBundleId: 'com.example.hoophub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyp1LwfVUlxErzDHHmTo4HkMD9Q1HyXqQ',
    appId: '1:663055197483:ios:5bff75e68e09dc93aa116e',
    messagingSenderId: '663055197483',
    projectId: 'hoophub-aa29d',
    storageBucket: 'hoophub-aa29d.appspot.com',
    iosBundleId: 'com.example.hoophub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpGMrtXJct-u-zXzvuaxZy-cTTbrqq6Fs',
    appId: '1:663055197483:web:cd34334b8f81493daa116e',
    messagingSenderId: '663055197483',
    projectId: 'hoophub-aa29d',
    authDomain: 'hoophub-aa29d.firebaseapp.com',
    storageBucket: 'hoophub-aa29d.appspot.com',
    measurementId: 'G-94JJDQ2BVM',
  );
}
